name: Node.js package

on:
  release:
    types:
      - released
  workflow_call:
    secrets:
      NPM:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
          run_install: |
            args: [--frozen-lockfile]
      - name: Test
        run: pnpm test

  publish-github:
    name: Publish to GitHub Package Registry
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
          run_install: |
            args: [--frozen-lockfile]
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          scope: ${{github.repository_owner}}
          registry-url: https://npm.pkg.github.com/
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    name: Publish to npm
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
          run_install: |
            args: [--frozen-lockfile]
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          scope: ${{github.repository_owner}}
          registry-url: https://registry.npmjs.org/
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
